import type { Metadata } from "next";
import { Cabin, Work_Sans } from "next/font/google";
import "./globals.css";

const cabin = Cabin({ subsets: ["latin"] });
const work_sans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* className={work_sans.className} */}
      <body>{children}</body>
    </html>
  );
}
